### ISSUE TITLE
WP site gone after I installed

### ISSUE THREAD

**Issue by JonSymons** [inpsyde/woocommerce-multisite-persistent-cart#1]
Installed the plugin via the upload .zip file function in my WP installs as I was having the exact problem with shopping cart data getting mixed across my two sites on the same domain.

After installation, the entire site, gone. Every page blank, no source code.

Help!

**Comment by JonSymons** [comment]
Deleted the plugin and site is back.

**Comment by JonSymons** [comment]
btw... WP Version 4.7.3

**Comment by dnaber-de** [comment]
I'm sorry that you broke your site but the README is [very clear](https://github.com/inpsyde/woocommerce-multisite-persistent-cart#installation) about how you have to install the plugin:

```
$ composer require inpsyde/woocommerce-multisite-persistent-cart
```

However, it's also possible to run this plugin in a stand-alone way if you don't have a full composer controlled environment. You have to clone/download the plugin and build the autoloader afterwards (from within the plugin's directory):

```
$ composer dump-autoload
```

Then ship the complete directory (including the `vendor` directory) of the plugin.
